version: "3"
services:
  api:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver [::]:8200"
    ports:
      - "8200:8200"
    stdin_open: true
    tty: true
    restart: always