# Generated by Django 3.2.6 on 2021-08-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('game_position', models.CharField(default='', max_length=50)),
                ('nationality', models.CharField(default='', max_length=50)),
                ('team', models.CharField(default='', max_length=50)),
            ],
            options={
                'managed': 'api_gamer',
            },
        ),
    ]
